### ISSUE TITLE
 Add Custom Certs To Browser That Takes The Screenshot

### ISSUE THREAD

**Issue by FliKites** [robvanderleek/capture-website-api#289]
Would be useful to add in a function/reconfigure to allow custom certs to be installed into the browser that is taking the screenshots.

**Comment by robvanderleek** [comment]
Hi @FliKites 

I guess custom certs could be included when building the Docker image, or do you need more flexibility?
In general I'm interested in your use-case for this feature 🙂 

KR, Rob

**Comment by FliKites** [comment]
So over the last week I've been testing out self signed certs in a fork and haven't been able to get a fully "secured" environment working. The cert is being generated from https://github.com/buffrr/letsdane, but I've tried all of the possible methods available to get nodejs to trust the cert. No luck though, I have to revert to using hacks that bypass checking the authenticity of the cert using DNSSEC. For example using arguments in the browser options to ignore cert errors.

**Comment by robvanderleek** [comment]
I only have a basic understanding of browser TLS certificates so I'm afraid I can't offer a lot of help here.
Let me know if you have any general questions about the repo.
I'l leave this issue open, feel free to close it of course if it's not possible to implement this in a way that satisfies your use-case.
