### ISSUE TITLE
please update fetch with cors version

### ISSUE THREAD

**Issue by darwinprayoga** [robvanderleek/capture-website-api#337]

**Comment by robvanderleek** [comment]
Hi @darwinprayoga 👋 

Unfortunately the issue title is not clear to me.
Can you perhaps describe a use-case of what you're trying to achieve with this project? Or something that currently does not work as expected?

**Comment by darwinprayoga** [comment]
i used Fresh js by deno, u can try

**Comment by robvanderleek** [comment]
Unfortunately your problem is still not clear to me.
Are you trying to run this project with Deno? Or perhaps trying to screenshot a website mede with Fresh JS?
I haven't used Fresh or Deno before myself.

Please try to give as much details as possible otherwise I'm afraid I can't be of any help.

**Comment by darwinprayoga** [comment]
on fetch got an error, request for cors-policy too

**Comment by robvanderleek** [comment]
I tried to screenshot https://fresh.deno.dev/ and that worked fine:

```shell
curl 'https://capture-website-api.herokuapp.com/capture?url=https://fresh.deno.dev/' -o screenshot.png
```

but maybe that's not what you mean.

I developed the code to run under NodeJS 16, maybe it does not run under Deno but that's not a target platform at the moment.
